apiVersion: apps/v1
kind: Deployment
metadata:
  name: brokerone-kafka-dispatcher-local
  namespace: local
  labels:
    app: brokerone-kafka-dispatcher-local
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: brokerone-kafka-dispatcher-local
  template:
    metadata:
      labels:
        app: brokerone-kafka-dispatcher-local
    spec:
      serviceAccountName: dispatcher-sa
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 25
      enableServiceLinks: false
      containers:
        - name: dispatcher
          image: broker-app-worker-base:local
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_NAMESPACE
              value: local
            - name: KAFKA_JOB_IMAGE
              value: broker-app-worker-base:local
            - name: KAFKA_JOB_IMAGE_PULL_POLICY
              value: IfNotPresent
            - name: KAFKA_JOB_CPU_LIMIT
              value: "0.5"
            - name: KAFKA_JOB_MEMORY_LIMIT
              value: "512Mi"
            - name: KAFKA_JOB_CPU_REQUEST
              value: "0.1"
            - name: KAFKA_JOB_MEMORY_REQUEST
              value: "300Mi"
            - name: KAFKA_SECRET_REF
              value: brokerone-kafka-dispatcher-keys-local
            - name: KAFKA_DISPATCHER_GROUP
              value: brokerone-dispatcher-group-local
            - name: KAFKA_MAX_CONCURRENT_JOBS
              value: "3"
            - name: KAFKA_JOB_TTL_SECONDS
              value: "300"
            - name: KAFKA_JOB_ACTIVE_DEADLINE_SECONDS
              value: "300"
            - name: ARGOCD_APP_INSTANCE
              value: brokerone-kafka-dispatcher-local
          envFrom:
            - secretRef:
                name: brokerone-kafka-dispatcher-keys-local
          resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: "0.1"
              memory: 300Mi